### ISSUE TITLE
`Esc` executes `copilot_reject_completion` when there is no visible Copilot suggestion

### ISSUE THREAD

**Issue by jfcherng** [TheSecEng/LSP-copilot#25]
I occasionally noticed that my `Esc` key won't remove multi cursors. That functionality is provided in ST default keybinding.

```js
	{ "keys": ["escape"], "command": "single_selection", "context":
		[
			{ "key": "num_selections", "operator": "not_equal", "operand": 1 }
		]
	},
```

It's gotten override by `copilot_reject_completion` somehow when obviously there is no Copilot suggestion visible.

```js
    {
        "keys": ["escape"],
        "command": "copilot_reject_completion",
        "context": [{ "key": "setting.copilot.completion.is_visible" }]
    },
```

This means something may go wrong with our status management of a view: why `is_visible` is `True` when there is no popup visible? Likely some async things?

I don't have a reliable way to reproduce this but just make a log for it here.

**Comment by timfjord** [comment]
I also had something similar but with the tab key.

**Comment by timfjord** [comment]
I was able to reproduce this issue quite often and when I checked `view.settings().get('copilot.completion.is_visible')` it returned `True` even that the completion was hidden.

So it definitely has to do with how we hide the completion
