### ISSUE TITLE
Copilot.vim 1.5.0

### ISSUE THREAD

**Issue by jfcherng** [TheSecEng/LSP-copilot#49]
https://github.com/github/copilot.vim/commit/da286d8c52159026f9cba16cd0f98b609c056841

Not sure what new things are or there is no new thing.

**Comment by TheSecEng** [comment]
@jfcherng Nothing new from an `agent.js` perspective. Just some formatting change.

The plugin has implemented something called `CopilotAnnotations`

**Comment by jfcherng** [comment]
That's great ;)
