### ISSUE TITLE
`Copilot: Sign In` is missing from the command palette 

### ISSUE THREAD

**Issue by eidellev** [TheSecEng/LSP-copilot#58]
Thank you for making this!

I'm trying to get started but the `Copilot: Sign In` command is missing.

**Comment by jfcherng** [comment]
Any error in ST console?

**Comment by eidellev** [comment]
thank you for the swift response. no errors, but ST becomes a bit unresponsive when I enable `LSP-copilot`.

**Comment by jfcherng** [comment]
then I think you are hitting this https://github.com/TheSecEng/LSP-copilot/issues/51

**Comment by eidellev** [comment]
Thanks, it worked. Sorry about the duplicate issue 🙏
